#Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
#Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that 
#the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed 
#correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” 
#and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the 
#number of guesses the user makes throughout teh game and tell the user at the end.
#
#Say the number generated by the computer is 1038. An example interaction could look like this:
#
#  Welcome to the Cows and Bulls Game! 
#  Enter a number: 
#  >>> 1234
#  2 cows, 0 bulls
#  >>> 1256
#  1 cow, 1 bull
#  ...
#
#Until the user guesses the number.

def getCows(generated,guessed):
    cows = 0
    for i in range(0,4):
        if generated[i] == guessed[i]:
            cows+=1
    return cows

def getBulls(generated,guessed):
    bulls = 0
    for i in range(0,4):
        if guessed[i] in generated and guessed[i] != generated[i]:
            bulls+=1
    return bulls

if __name__ == "__main__":
    from random import randint

    play = True
    totalWins = 0

    while play:
        cows = 0
        bulls = 0
        continueGuessing = True
        generated = str(randint(1000,9999))
        while continueGuessing:
            correctInput = False
            while not correctInput:
                guessed = input("Guess a 4 digits number: ")
                if len(guessed) != 4:
                    print("It must be a 4 digits number.")
                else:
                    correctInput = True
            if guessed == generated:
                print("You guessed the number!")
                totalWins += 1
                continueGuessing = False
                correctInputPlay = False
                while not correctInputPlay:
                    continuePlaying = input("Do you want to play again? (yes/no): ")
                    if continuePlaying.lower() == "yes":
                        play = True
                        correctInputPlay = True
                    elif continuePlaying.lower() == "no":
                        correctInputPlay = True
                        play = False
                        print("You guessed correctly {0} times!".format(totalWins))
                    else:
                        print("Only valid inputs are 'yes' or 'no'.")
            else:
                correctInput = False
                cows += getCows(generated,guessed)
                bulls += getBulls(generated,guessed)
                print("You've got {0} cows and {1} bulls!".format(cows,bulls))